### ISSUE TITLE
Conver original pdf to original img

### ISSUE THREAD

**Issue by lolpa1n** [machine-intelligence-laboratory/DDI-100#9]
Hello, i try convert original pdf to images, and ran into a problem, at first I thought that in the names of the box files this is the page number on the pdf, but this only works with documents up to 10 pages, then there is a confusion with the indices, but I was also able to decode this and match the boxes. But then I also discovered that many pages are simply skipped, for example, for 2.pkl, page number 10 corresponds

Is there any way to get it right?

of course, i can get the original by the mask, background and text, but then the text turns out to be slightly distorted

**Comment by spairet** [comment]
Unfortunately, during creation of the dataset, some pages of the original pdfs where removed due to inconsistent box allocation and then pages for renumbered.
If you need to restore original pdf pages, you can compile them from original backgrounds and texts: `orig_backgrounds/*.png` and `orig_texts/*.png`
